#
# Site settings
#

version: 1.1

gems:
  - jekyll-coffeescript
  - jekyll-paginate

title: imapfw community's website
email: offlineimap-project@lists.alioth.debian.org
baseurl: "/imapfw.github.io/" # the subpath of your site, e.g. /blog/
url: "http://imapfw.offlineimap.org"
description: > # this means it ignores newlines until next key
  imapfw community's website.

permalink: /:year/:month/:day/:title/

# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/OfflineIMAP/imapfw.github.io/blob/gh-pages/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/OfflineIMAP/imapfw.github.io/new/gh-pages

#
# Build settings
#
github: [Repository metadata]
#paginate: 10
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

#
# Build settings we can't change.
#
highlighter: rouge
lsi: false
safe: true
#source: [your repo's top level directory]
#incremental: false
gist:
  noscript: false

#
# Posts
#
excerpt_separator: <!--more-->

github_username: OfflineIMAP
twitter_username: OfflineIMAP

collections:
  doc:
    output: true
  gsoc:
    output: true
